### ISSUE TITLE
User Sync wasCreated is failing to return true on successful create

### ISSUE THREAD

**Issue by sjakos** [permitio/permit-java#27]
Does this TODO need to be done for sync to work?

https://github.com/permitio/permit-java/blob/906451782245a82cb08294bfe5bd53cfee3eeb92/src/main/java/io/permit/sdk/api/UsersApi.java#L255

**Comment by orweis** [comment]
Probably unrelated. 
If you have an issue with the SDK please provide the flow you are doing with it, exceptions, and logs etc. to enable investigation on our side.

**Comment by sjakos** [comment]
Here's a snippet of how I'm using sync. I have users that are coming from a couple different systems and don't have a way to reliably sync them into Permit directly, but I trust the JWTs and want to sync the users to perform checks throughout the rest of my API.

```java
final User user = new User.Builder(jwt.getClaimAsString("sub")).build();
try {
   log.debug("Syncing user with ID {} into Permit", user.getKey());
   final CreateOrUpdateResult<UserRead> result = permit.api.users.sync(user);

    //  If this is set to !result.wasCreated() this works as expected
   if (result.wasCreated()) {
     final String roleKey =
      "org_1234".equals(jwt.getClaimAsString("org_id")) ? "owner" : "viewer";

     log.debug("Assigning {} role to user with ID {}", roleKey, user.getKey());
     permit.api.users.assignRole(claims.subject(), roleKey, "default");
   }
 } catch (IOException | PermitApiError | PermitContextError ex) {
   log.error("Unable to sync user with Permit", ex);
   return false;
}
```

**Comment by omer9564** [comment]
Hey @sjakos, looks like the TODO needs to be done in order for the wasCreated to reflect the real scenario.
Anyway from a look at your code snippet, it looks to me that what you want is to sync user with role assignments:
- in case it is a new user, assign the roles
- in case it is an old user, you assume the roles are already assigned (?) 
If I'm correct, you can use the `roleAssignments` attribute on the UserCreate class to pass the role assignments you want to add to the user.

**Comment by sjakos** [comment]
Okay, that's helpful. I'll try out the role assignment on create.

**Comment by EliMoshkovich** [comment]
Hi @sjakos,

The new version 2.1.0 has been released, and it includes the change from a 200 response to a 201 response, as you mentioned earlier in this thread.
